name: Genereer SBOM

on: [push]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installeer CycloneDX
        run: npm install -g @cyclonedx/bom

      - name: Genereer SBOM
        run: cyclonedx-bom -o sbom.json

      - name: Toon SBOM inhoud
        run: cat sbom.json
