name: Generate SBOM

on:
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install project dependencies
        run: npm install

      - name: Install CycloneDX CLI
        run: npm install --no-save cyclonedx-node-module

      - name: Generate SBOM
        run: npx cyclonedx-bom -o sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: juice-shop-sbom
          path: sbom.json


