name: Generate SBOM

on:
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker (nodig op GitHub runner)
        run: sudo apt-get update && sudo apt-get install -y docker.io

      - name: Generate CycloneDX SBOM via Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/src cyclonedx/cyclonedx-npm -o /src/sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json



