name: Genereer SBOM

on: [push]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Genereer SBOM met CycloneDX
        uses: CycloneDX/gh-node-module-generatebom@v1

